### ISSUE TITLE
[window deco kcm]: crashing system settings

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#63]
steps to reproduce crash:

- add at least 2 themes from GHNS (like Beo or FormaN)
- select a theme and press "Apply"
- press "Overview" button to return to System Settings: Crash

**Comment by davidedmundson** [comment]
Backtrace for future me

Thread 1 (Thread 0x7f32a9cb47c0 (LWP 1667)):
[KCrash Handler]
#6  0x00007f3288093657 in QV4::RegExpCache::~RegExpCache (this=0x1db6ac0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/qml/jsruntime/qv4regexp.cpp:45
#7  0x00007f328802f76c in QV4::ExecutionEngine::~ExecutionEngine (this=0x1dcd1a0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/qml/jsruntime/qv4engine.cpp:436
#8  0x00007f32881b78ae in QV8Engine::~QV8Engine (this=0x1ddf9b0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/qml/qml/v8/qv8engine.cpp:159
#9  0x00007f32881b793a in QV8Engine::~QV8Engine (this=0x1ddf9b0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/qml/qml/v8/qv8engine.cpp:160
#10 0x00007f3287faeafa in QJSEngine::~QJSEngine (this=0x1dc7440, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/qml/jsapi/qjsengine.cpp:203
#11 0x00007f32880fbd81 in QQmlEngine::~QQmlEngine (this=0x1dc7440, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/qml/qml/qqmlengine.cpp:899
#12 0x00007f32880fbdb0 in QQmlEngine::~QQmlEngine (this=0x1dc7440, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/qml/qml/qqmlengine.cpp:922
#13 0x00007f3285172747 in QScopedPointerDeleter<QQmlEngine>::cleanup(QQmlEngine*) () from /opt/kde5/lib64/plugins/org.kde.kdecoration2/kwin5_aurorae.so
#14 0x00007f3285170175 in QScopedPointer<QQmlEngine, QScopedPointerDeleter<QQmlEngine> >::reset(QQmlEngine*) () from /opt/kde5/lib64/plugins/org.kde.kdecoration2/kwin5_aurorae.so
#15 0x00007f328516753d in Aurorae::Helper::unref() () from /opt/kde5/lib64/plugins/org.kde.kdecoration2/kwin5_aurorae.so
#16 0x00007f3285168aa6 in Aurorae::Decoration::~Decoration() () from /opt/kde5/lib64/plugins/org.kde.kdecoration2/kwin5_aurorae.so
#17 0x00007f3285168cb6 in Aurorae::Decoration::~Decoration() () from /opt/kde5/lib64/plugins/org.kde.kdecoration2/kwin5_aurorae.so
#18 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x37bba90) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#19 0x00007f32a5744908 in QObject::~QObject (this=0x37bba10, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1030
#20 0x00007f3287a88aee in QQuickItem::~QQuickItem (this=0x37bba10, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quick/items/qquickitem.cpp:2225
#21 0x00007f3287afd483 in QQuickPaintedItem::~QQuickPaintedItem (this=0x37bba10, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quick/items/qquickpainteditem.cpp:157
#22 0x00007f3285e1fc12 in KDecoration2::Preview::PreviewItem::~PreviewItem() () from /opt/kde5/lib64/qml/org/kde/kwin/private/kdecoration/libkdecorationprivatedeclarative.so
#23 0x00007f3285e2bf39 in QQmlPrivate::QQmlElement<KDecoration2::Preview::PreviewItem>::~QQmlElement() () from /opt/kde5/lib64/qml/org/kde/kwin/private/kdecoration/libkdecorationprivatedeclarative.so
#24 0x00007f3285e2bf72 in QQmlPrivate::QQmlElement<KDecoration2::Preview::PreviewItem>::~QQmlElement() () from /opt/kde5/lib64/qml/org/kde/kwin/private/kdecoration/libkdecorationprivatedeclarative.so
#25 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x21fd1f0) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#26 0x00007f32a5744908 in QObject::~QObject (this=0x21fd1c0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1030
#27 0x00007f3287a88aee in QQuickItem::~QQuickItem (this=0x21fd1c0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quick/items/qquickitem.cpp:2225
#28 0x00007f3287afcb5f in QQmlPrivate::QQmlElement<QQuickItem>::~QQmlElement (this=0x21fd1c0, __in_chrg=<optimized out>) at ../../include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#29 0x00007f3287afcb98 in QQmlPrivate::QQmlElement<QQuickItem>::~QQmlElement (this=0x21fd1c0, __in_chrg=<optimized out>) at ../../include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#30 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x21fcda0) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#31 0x00007f32a5744908 in QObject::~QObject (this=0x21fcc70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1030
#32 0x00007f3287a88aee in QQuickItem::~QQuickItem (this=0x21fcc70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quick/items/qquickitem.cpp:2225
#33 0x00007f3286055e82 in QQuickLayout::~QQuickLayout (this=0x21fcc70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtquickcontrols/src/layouts/qquicklayout.cpp:517
#34 0x00007f3286056741 in QQuickGridLayoutBase::~QQuickGridLayoutBase (this=0x21fcc70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtquickcontrols/src/layouts/qquicklinearlayout.cpp:320
#35 0x00007f3286051170 in QQuickLinearLayout::~QQuickLinearLayout (this=0x21fcc70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtquickcontrols/src/layouts/qquicklinearlayout_p.h:192
#36 0x00007f3286052f0c in QQuickRowLayout::~QQuickRowLayout (this=0x21fcc70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtquickcontrols/src/layouts/qquicklinearlayout_p.h:224
#37 0x00007f328605522d in QQmlPrivate::QQmlElement<QQuickRowLayout>::~QQmlElement (this=0x21fcc70, __in_chrg=<optimized out>) at /home/david/projects/kde5/build/qt/qtdeclarative/include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#38 0x00007f3286055266 in QQmlPrivate::QQmlElement<QQuickRowLayout>::~QQmlElement (this=0x21fcc70, __in_chrg=<optimized out>) at /home/david/projects/kde5/build/qt/qtdeclarative/include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#39 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x37c1b00) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#40 0x00007f32a5744908 in QObject::~QObject (this=0x37bb350, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1030
#41 0x00007f3287a88aee in QQuickItem::~QQuickItem (this=0x37bb350, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quick/items/qquickitem.cpp:2225
#42 0x00007f3287afcb5f in QQmlPrivate::QQmlElement<QQuickItem>::~QQmlElement (this=0x37bb350, __in_chrg=<optimized out>) at ../../include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#43 0x00007f3287afcb98 in QQmlPrivate::QQmlElement<QQuickItem>::~QQmlElement (this=0x37bb350, __in_chrg=<optimized out>) at ../../include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#44 0x00007f32881fdae7 in QQmlDelegateModel::~QQmlDelegateModel (this=0x1c42100, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/qml/types/qqmldelegatemodel.cpp:233
#45 0x00007f32881fdc5e in QQmlDelegateModel::~QQmlDelegateModel (this=0x1c42100, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/qml/types/qqmldelegatemodel.cpp:247
#46 0x00007f3287bb19a9 in QQuickItemView::~QQuickItemView (this=0x1c18a80, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quick/items/qquickitemview.cpp:258
#47 0x00007f3287b61d76 in QQuickListView::~QQuickListView (this=0x1c18a80, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quick/items/qquicklistview.cpp:1790
#48 0x00007f3287afcad1 in QQmlPrivate::QQmlElement<QQuickListView>::~QQmlElement (this=0x1c18a80, __in_chrg=<optimized out>) at ../../include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#49 0x00007f3287afcb0a in QQmlPrivate::QQmlElement<QQuickListView>::~QQmlElement (this=0x1c18a80, __in_chrg=<optimized out>) at ../../include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#50 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x1c1e7f0) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#51 0x00007f32a5744908 in QObject::~QObject (this=0x1c1e7c0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1030
#52 0x00007f3287a88aee in QQuickItem::~QQuickItem (this=0x1c1e7c0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quick/items/qquickitem.cpp:2225
#53 0x00007f3287abbb1e in QQuickFocusScope::~QQuickFocusScope (this=0x1c1e7c0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quick/items/qquickfocusscope.cpp:59
#54 0x00007f3287afce77 in QQmlPrivate::QQmlElement<QQuickFocusScope>::~QQmlElement (this=0x1c1e7c0, __in_chrg=<optimized out>) at ../../include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#55 0x00007f3287afceb0 in QQmlPrivate::QQmlElement<QQuickFocusScope>::~QQmlElement (this=0x1c1e7c0, __in_chrg=<optimized out>) at ../../include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#56 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x1b4d120) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#57 0x00007f32a5744908 in QObject::~QObject (this=0x1c02e70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1030
#58 0x00007f3287a88aee in QQuickItem::~QQuickItem (this=0x1c02e70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quick/items/qquickitem.cpp:2225
#59 0x00007f3286055e82 in QQuickLayout::~QQuickLayout (this=0x1c02e70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtquickcontrols/src/layouts/qquicklayout.cpp:517
#60 0x00007f3286056741 in QQuickGridLayoutBase::~QQuickGridLayoutBase (this=0x1c02e70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtquickcontrols/src/layouts/qquicklinearlayout.cpp:320
#61 0x00007f3286051170 in QQuickLinearLayout::~QQuickLinearLayout (this=0x1c02e70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtquickcontrols/src/layouts/qquicklinearlayout_p.h:192
#62 0x00007f32860532dc in QQuickColumnLayout::~QQuickColumnLayout (this=0x1c02e70, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtquickcontrols/src/layouts/qquicklinearlayout_p.h:239
#63 0x00007f328605519f in QQmlPrivate::QQmlElement<QQuickColumnLayout>::~QQmlElement (this=0x1c02e70, __in_chrg=<optimized out>) at /home/david/projects/kde5/build/qt/qtdeclarative/include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#64 0x00007f32860551d8 in QQmlPrivate::QQmlElement<QQuickColumnLayout>::~QQmlElement (this=0x1c02e70, __in_chrg=<optimized out>) at /home/david/projects/kde5/build/qt/qtdeclarative/include/QtQml/../../../../../qt5/qtdeclarative/src/qml/qml/qqmlprivate.h:98
#65 0x00007f3289dd1ffe in QQuickWidget::~QQuickWidget (this=0x19cff00, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quickwidgets/qquickwidget.cpp:395
#66 0x00007f3289dd205a in QQuickWidget::~QQuickWidget (this=0x19cff00, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtdeclarative/src/quickwidgets/qquickwidget.cpp:397
#67 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x10df960) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#68 0x00007f32a6837eb7 in QWidget::~QWidget (this=0x1b06ba0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:1642
#69 0x00007f3287680a23 in KDecoration2::Configuration::ConfigurationForm::~ConfigurationForm() () from /opt/kde5/lib64/plugins/kcm_kwindecoration.so
#70 0x00007f3287680a5c in KDecoration2::Configuration::ConfigurationForm::~ConfigurationForm() () from /opt/kde5/lib64/plugins/kcm_kwindecoration.so
#71 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x1aa1850) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#72 0x00007f32a6837eb7 in QWidget::~QWidget (this=0x19fe890, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:1642
#73 0x00007f32a7f4f9eb in KCModule::~KCModule (this=0x19fe890, __in_chrg=<optimized out>) at /home/david/projects/kde5/src/frameworks/kconfigwidgets/src/kcmodule.cpp:164
#74 0x00007f328767746e in KDecoration2::Configuration::ConfigurationModule::~ConfigurationModule() () from /opt/kde5/lib64/plugins/kcm_kwindecoration.so
#75 0x00007f32876774a6 in KDecoration2::Configuration::ConfigurationModule::~ConfigurationModule() () from /opt/kde5/lib64/plugins/kcm_kwindecoration.so
#76 0x00007f32a95e7e9a in KCModuleProxy::deleteClient (this=0x1a13940) at /home/david/projects/kde5/src/frameworks/kcmutils/src/kcmoduleproxy.cpp:214
#77 0x00007f32a95e7da2 in KCModuleProxy::~KCModuleProxy (this=0x1a13940, __in_chrg=<optimized out>) at /home/david/projects/kde5/src/frameworks/kcmutils/src/kcmoduleproxy.cpp:205
#78 0x00007f32a95e7e3e in KCModuleProxy::~KCModuleProxy (this=0x1a13940, __in_chrg=<optimized out>) at /home/david/projects/kde5/src/frameworks/kcmutils/src/kcmoduleproxy.cpp:209
#79 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x1a10230) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#80 0x00007f32a6837eb7 in QWidget::~QWidget (this=0x1a0eaf0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:1642
#81 0x00007f32a6837fce in QWidget::~QWidget (this=0x1a0eaf0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:1662
#82 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x1a0ff90) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#83 0x00007f32a6837eb7 in QWidget::~QWidget (this=0x1a0ecb0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:1642
#84 0x00007f32a699f2dc in QFrame::~QFrame (this=0x1a0ecb0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qframe.cpp:209
#85 0x00007f32a6a3c5df in QAbstractScrollArea::~QAbstractScrollArea (this=0x1a0ecb0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qabstractscrollarea.cpp:577
#86 0x00007f32a6a42f58 in QScrollArea::~QScrollArea (this=0x1a0ecb0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qscrollarea.cpp:166
#87 0x00007f32a6a42f8e in QScrollArea::~QScrollArea (this=0x1a0ecb0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qscrollarea.cpp:168
#88 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x18c3600) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#89 0x00007f32a6837eb7 in QWidget::~QWidget (this=0x10b3dd0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:1642
#90 0x00007f32a699f2dc in QFrame::~QFrame (this=0x10b3dd0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qframe.cpp:209
#91 0x00007f32a6a102ee in QStackedWidget::~QStackedWidget (this=0x10b3dd0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qstackedwidget.cpp:141
#92 0x00007f32a6fc8593 in KPageStackedWidget::~KPageStackedWidget (this=0x10b3dd0, __in_chrg=<optimized out>) at /home/david/projects/kde5/src/frameworks/kwidgetsaddons/src/kpageview_p.h:37
#93 0x00007f32a6fc85cc in KPageStackedWidget::~KPageStackedWidget (this=0x10b3dd0, __in_chrg=<optimized out>) at /home/david/projects/kde5/src/frameworks/kwidgetsaddons/src/kpageview_p.h:37
#94 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x18c3260) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#95 0x00007f32a6837eb7 in QWidget::~QWidget (this=0x10b3c60, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:1642
#96 0x00007f32a6fc6ed4 in KPageView::~KPageView (this=0x10b3c60, __in_chrg=<optimized out>) at /home/david/projects/kde5/src/frameworks/kwidgetsaddons/src/kpageview.cpp:331
#97 0x00007f32a6fcbd3a in KPageWidget::~KPageWidget (this=0x10b3c60, __in_chrg=<optimized out>) at /home/david/projects/kde5/src/frameworks/kwidgetsaddons/src/kpagewidget.cpp:78
#98 0x00007f32a6fcbd70 in KPageWidget::~KPageWidget (this=0x10b3c60, __in_chrg=<optimized out>) at /home/david/projects/kde5/src/frameworks/kwidgetsaddons/src/kpagewidget.cpp:80
#99 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x18c2f30) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#100 0x00007f32a6837eb7 in QWidget::~QWidget (this=0x116c6d0, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:1642
#101 0x00007f32a9a75c89 in ModuleView::~ModuleView() () from /opt/kde5/lib64/libsystemsettingsview.so.3
#102 0x00007f32a9a75cc2 in ModuleView::~ModuleView() () from /opt/kde5/lib64/libsystemsettingsview.so.3
#103 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x18c2ba0) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#104 0x00007f32a6837eb7 in QWidget::~QWidget (this=0x1185f10, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:1642
#105 0x00007f32a699f2dc in QFrame::~QFrame (this=0x1185f10, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qframe.cpp:209
#106 0x00007f32a6a102ee in QStackedWidget::~QStackedWidget (this=0x1185f10, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qstackedwidget.cpp:141
#107 0x00007f32a6a10324 in QStackedWidget::~QStackedWidget (this=0x1185f10, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qstackedwidget.cpp:143
#108 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x105f610) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#109 0x00007f32a6837eb7 in QWidget::~QWidget (this=0x1092d90, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:1642
#110 0x00007f32a699f2dc in QFrame::~QFrame (this=0x1092d90, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qframe.cpp:209
#111 0x00007f32a6a102ee in QStackedWidget::~QStackedWidget (this=0x1092d90, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qstackedwidget.cpp:141
#112 0x00007f32a6a10324 in QStackedWidget::~QStackedWidget (this=0x1092d90, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qstackedwidget.cpp:143
#113 0x00007f32a57462f0 in QObjectPrivate::deleteChildren (this=0x108ae80) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1950
#114 0x00007f32a6837eb7 in QWidget::~QWidget (this=0x108f790, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:1642
#115 0x00007f32a69bb052 in QMainWindow::~QMainWindow (this=0x108f790, __in_chrg=<optimized out>) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qmainwindow.cpp:379
#116 0x00007f32a863ea0b in KMainWindow::~KMainWindow (this=0x108f790, __in_chrg=<optimized out>) at /home/david/projects/kde5/src/frameworks/kxmlgui/src/kmainwindow.cpp:332
#117 0x00007f32a867f5f6 in KXmlGuiWindow::~KXmlGuiWindow (this=0x108f790, __vtt_parm=0x62aa68 <VTT for SettingsBase+8>, __in_chrg=<optimized out>) at /home/david/projects/kde5/src/frameworks/kxmlgui/src/kxmlguiwindow.cpp:110
#118 0x000000000041718c in SettingsBase::~SettingsBase() ()
#119 0x00000000004171fa in SettingsBase::~SettingsBase() ()
#120 0x00007f32a574d256 in qDeleteInEventHandler (o=0x108f790) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:4390
#121 0x00007f32a5744c6c in QObject::event (this=0x108f790, e=0x3d5ce90) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qobject.cpp:1236
#122 0x00007f32a684c0ec in QWidget::event (this=0x108f790, event=0x3d5ce90) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qwidget.cpp:9083
#123 0x00007f32a69bd1a8 in QMainWindow::event (this=0x108f790, event=0x3d5ce90) at /home/david/projects/kde5/qt5/qtbase/src/widgets/widgets/qmainwindow.cpp:1495
#124 0x00007f32a8640dbd in KMainWindow::event (this=0x108f790, ev=0x3d5ce90) at /home/david/projects/kde5/src/frameworks/kxmlgui/src/kmainwindow.cpp:825
#125 0x00007f32a867f7e7 in KXmlGuiWindow::event (this=0x108f790, ev=0x3d5ce90) at /home/david/projects/kde5/src/frameworks/kxmlgui/src/kxmlguiwindow.cpp:118
#126 0x00007f32a67fb538 in QApplicationPrivate::notify_helper (this=0xf7f5a0, receiver=0x108f790, e=0x3d5ce90) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qapplication.cpp:3722
#127 0x00007f32a67fb3a4 in QApplication::notify (this=0x7fff44bc9c20, receiver=0x108f790, e=0x3d5ce90) at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qapplication.cpp:3687
#128 0x00007f32a57082b6 in QCoreApplication::notifyInternal (this=0x7fff44bc9c20, receiver=0x108f790, event=0x3d5ce90) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qcoreapplication.cpp:930
#129 0x00007f32a570bf17 in QCoreApplication::sendEvent (receiver=0x108f790, event=0x3d5ce90) at ../../include/QtCore/../../../../../qt5/qtbase/src/corelib/kernel/qcoreapplication.h:228
#130 0x00007f32a57095ef in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0xf7ee50) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qcoreapplication.cpp:1534
#131 0x00007f32a5708f9e in QCoreApplication::sendPostedEvents (receiver=0x0, event_type=0) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qcoreapplication.cpp:1392
#132 0x00007f32a5780df4 in postEventSourceDispatch (s=0xfc3ae0) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:271
#133 0x00007f32a1c8fa0d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#134 0x00007f32a1c8fcf8 in ?? () from /usr/lib/libglib-2.0.so.0
#135 0x00007f32a1c8fdac in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#136 0x00007f32a57815af in QEventDispatcherGlib::processEvents (this=0xfc4680, flags=...) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:418
#137 0x00007f329bb58432 in QPAEventDispatcherGlib::processEvents (this=0xfc4680, flags=...) at /home/david/projects/kde5/qt5/qtbase/src/platformsupport/eventdispatchers/qeventdispatcher_glib.cpp:115
#138 0x00007f32a5704f5a in QEventLoop::processEvents (this=0x7fff44bc9b40, flags=...) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qeventloop.cpp:128
#139 0x00007f32a5705233 in QEventLoop::exec (this=0x7fff44bc9b40, flags=...) at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qeventloop.cpp:204
#140 0x00007f32a5708990 in QCoreApplication::exec () at /home/david/projects/kde5/qt5/qtbase/src/corelib/kernel/qcoreapplication.cpp:1183
#141 0x00007f32a60b0a78 in QGuiApplication::exec () at /home/david/projects/kde5/qt5/qtbase/src/gui/kernel/qguiapplication.cpp:1507
#142 0x00007f32a67f84d5 in QApplication::exec () at /home/david/projects/kde5/qt5/qtbase/src/widgets/kernel/qapplication.cpp:2956
#143 0x00000000004216fc in main ()

**Comment by davidedmundson** [comment]
Interestingly we have the same crash reported in a completely unrelated area of Plasma.
https://bugs.kde.org/show_bug.cgi?id=338890

We delete a QQmlEngine and then the same thing is happening.

**Comment by davidedmundson** [comment]
The underlying problem is super deep in Qt's JS engine.

I have a patch that bodges round it changing our behaviour so we don't hit it. https://paste.kde.org/pv8bqqz8k
I opened the kcmshell5 15 times in a row and it all seemed fine.

I'm pretty close to fixing it properly, which I think is worth doing given we've seen the same crash elsewhere but I need another day on it.

**Comment by mgraesslin** [comment]
The workaround seems fine to me independent of whether we get a fix into Qt or not (given that it's still some time and can hit many users).

**Comment by davidedmundson** [comment]
ok, is that a ship it? 
and I'll make sure it gets into netrunner packaging too

**Comment by mgraesslin** [comment]
> ok, is that a ship it? 

yes, for Plasma/5.2 branch

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4696114/+listing-archive-extra

**Comment by star-buck** [comment]
still crashing:
you open window deco kcm, you have two or more auorae themes installed, you pick one and apply.
Then you close and open kcm again, simply selecting (but not applying) the other aurorae theme, then close system settings window
The popup "Apply, Discard,Cancel comes up", you select Discard and the crash popup appears after system settings window closed.

**Comment by star-buck** [comment]
system settings is also crashing when:
* setting "widget theme" from qtcurve to breeze, then "apply"

switching from breeze to qtcurve works without crash

**Comment by star-buck** [comment]
anyone confirm those two scenarios above (window deco, widget deco) are still crashing system settings?

**Comment by davidedmundson** [comment]
Yeah, I've seen it :(

I thought my bodge was enough but clearly doesn't work enough with enough Auorae themes.

I have a definite patch for QtDeclaratiave that fixes the problem at the cause:
https://paste.kde.org/pmx8ewy10 and with this I haven't seen the crash with this.

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4766171/+listing-archive-extra

**Comment by davidedmundson** [comment]
Just tested that build on Netrunner. Apparently it's not fixing it.
Sorry.

Will spend another day on this. Stupid bloody thing.

**Comment by star-buck** [comment]
but the window deco crash seems fixed?

**Comment by davidedmundson** [comment]
Somehow that patch applied is off by one line.

The regexpcache should move not the regexpallocator.

It's possible I uploaded the wrong thing?  I did have to redo it from the test machine to my laptop to upload.. or maybe it got messed up when we made the packaging. 

Either way, it definitely has the wrong thing in debian/patches/fix-dtor-crash.patch compared with what I tested.

Harald could you rebuild with this.
https://paste.kde.org/pnmb47vec

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4766369/+listing-archive-extra

**Comment by star-buck** [comment]
seems fixed.

**Comment by star-buck** [comment]
and opened again, to test:
add some theme from GHNS (like Beo or FormaN), select theme and Apply, Hit "back" button to return to System Settings: Crash.

**Comment by davidedmundson** [comment]
I fixed it in a patch that went into Netrunner's version of Qt.

That patch does not seem to be in Kubuntu's version of Qt.

**Comment by star-buck** [comment]
right, still since anything not fixed in vivid would affect netrunner-16 yet again, it makes sense to re-open. So if a fix didnt reach upstream yet, we need to re-apply it anyway each time anew.

**Comment by apachelogger** [comment]
upstream ref?

**Comment by star-buck** [comment]
still occuring in netrunner 16: How can we patch/fix this again?

**Comment by star-buck** [comment]
@notmart : with David on the phone, can you have a look and let @apachelogger know?

**Comment by notmart** [comment]
sure

**Comment by notmart** [comment]
that patch should be definitely upstreamed...
A problem is that it is a crash that seems to be very difficult to reproduce in a simple test, that is something that is pretty much required to push the change in Qt.
this small app is as near i went replicating what the decoration kcm is doing
http://www.notmart.org/misc/qregexpcache.tar.bz2
but doesn't seem to crash

**Comment by star-buck** [comment]
So which patches need to be reapplied to which packages again by Harald to
make it work?

**Comment by notmart** [comment]
this one https://launchpadlibrarian.net/197096172/qtdeclarative-opensource-src_5.4.0-0ubuntu1~utopic1~ppa10%2Bnetrunner1_5.4.0-0ubuntu1~utopic1~ppa10%2Bnetrunner2.diff.gz

**Comment by star-buck** [comment]
okay, @apachelogger : lets try packaging this?

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-updates/+sourcepub/5059707/+listing-archive-extra

**Comment by apachelogger** [comment]
FWIW, I suggest to not close this issue if it works. This is going to crop up again for netrunner17 unless it gets resolved upstream, so we best not forget.

**Comment by star-buck** [comment]
@notmart: So now it crashes right away as soon as I try to open Window Decoration kcm...

**Comment by star-buck** [comment]
Here is what I found:
- This only seems to happen for "Widget Style" = "Breeze", anything else like Oxygen or MS Windows 9x will not crash the Window Decoration kcm?

**Comment by mgraesslin** [comment]
To my knowledge all crashers of window decoration configuration module are fixed with 5.4.3

**Comment by star-buck** [comment]
it still crashed on netrunner with plasma 5.4.3, but i cannot seem to reproduce it. I changed something and clicked "back" button, then it crashed... will close for now and reopen if happens again.
